_instantiator: pytorch_lightning.cli.instantiate_module
classes: 14
dropout: 0.3
freeze_classifier: false
freeze_window: false
learn_window: false
learning_rate: 0.0001
levels: null
optim: adam
patience: 10
pretrained: true
scheduler: null
state_dict_epoch: null
state_dict_id: null
weight_decay: null
widths: null
